export const CommunityCategoriesData = [
  {
    id: "1",
    name: "notification",
    field: "공지사항",
    field_jp: "공지사항",
    field_en: "Notification",
    route: "notification",
  },
  {
    id: "2",
    name: "events",
    field: "행사/특별공지",
    field_jp: "행사/특별공지",
    field_en: "Events",
    route: "events",
  },
  // {
  //   id: '3',
  //   name: 'free',
  //   field: '자유게시판',
  //   field_jp: '자유게시판',
  //   field_en: 'Free Board',
  //   route: 'free',
  // },
];

export const MoldCategoriesData = [
  {
    id: "1",
    name: "plastic-mold",
    field: "플라스틱사출금형",
    field_jp: "プラスチック",
    field_en: "Plastic Mold",
    route: "plastic-mold",
    sub: [
      {
        id: "1",
        name: "electronic",
        field: "전기 전자 OA",
        field_jp: "전기 전자 OA",
        field_en: "Electric-Electro OA",
        route: "electronic",
      },
      {
        id: "2",
        name: "auto",
        field: "자동차",
        field_jp: "자동차",
        field_en: "Autos",
        route: "auto",
      },
      {
        id: "3",
        name: "pachinko",
        field: "Pachinko  ",
        field_jp: "파친코 부품",
        field_en: "Pachinko",
        route: "pachinko",
      },
      {
        id: "4",
        name: "idea",
        field: "아이디어상품 기타",
        field_jp: "プラスチック",
        field_en: "Idea Products",
        route: "idea",
      },
      {
        id: "5",
        name: "post",
        field: "후가공  ",
        field_jp: "후가공",
        field_en: "Post Processing",
        route: "post",
      },
    ],
  },

  {
    id: "2",
    name: "press-mold",
    field: "프레스금형",
    field_jp: "プレス金型",
    field_en: "Press Mold",
    route: "press-mold",
    sub: [
      {
        id: "1",
        name: "electro",
        field: "전기 전자 OA",
        field_jp: "전기 전자 OA",
        field_en: "Electric-Electro OA",
        route: "electro",
      },
      {
        id: "2",
        name: "auto",
        field: "자동차 용품",
        field_jp: "자동차 용품",
        field_en: "Auto Supplies",
        route: "auto",
      },
      {
        id: "3",
        name: "misc",
        field: "기타",
        field_jp: "기타",
        field_en: "Misc",
        route: "misc",
      },
    ],
  },
  {
    id: "3",
    name: "mim",
    field: "금속사출성형",
    field_jp: "금속사출성형",
    field_en: "Metal Injection",
    route: "mim",
    sub: [],
  },
  {
    id: "4",
    name: "vacuum-mold",
    field: "진공성형 금형 ",
    field_jp: "真空成形",
    field_en: "Vacuum Injection",

    route: "vacuum-mold",
    sub: [],
  },
  {
    id: "5",
    name: "dicasting-mold",
    field: "다이캐스팅",
    field_jp: "ダイキャステ",
    field_en: "Dicasting",
    route: "dicasting-mold",
    sub: [],
  },
  {
    id: "6",
    name: "forging-mold",
    field: "단조 금형",
    field_jp: "단조금형",
    field_en: "Forging",
    route: "forging-mold",
    sub: [],
  },
  {
    id: "7",
    name: "blow-mold",
    field: "BLOW금형",
    field_jp: "BLOW金型   ",
    field_en: "Injection Blow",
    route: "blow-mold",
    sub: [],
  },
  {
    id: "8",
    name: "extrude-mold",
    field: "압출금형",
    field_jp: "押出 ",
    field_en: "Extrude",
    route: "extrude-mold",
    sub: [],
  },
  {
    id: "9",
    name: "rubber-mold",
    field: "고무금형",
    field_jp: "고무금형",
    field_en: "Rubber",
    route: "rubber-mold",
    sub: [],
  },
  {
    id: "10",
    name: "glass-mold",
    field: "유리금형",
    field_jp: "유리금형",
    field_en: "Glass",
    route: "glass-mold",
    sub: [],
  },
  {
    id: "11",
    name: "misc",
    field: "기타",
    field_jp: "기타",
    field_en: "Miscellaneous",
    route: "misc",
    sub: [],
  },
];
export const PrecisionCategoriesData = [
  {
    id: "1",
    name: "mechanical-metal",
    field: "기계가공-금속",
    field_jp: "기계가공-금속",
    field_en: "Mechanial Process-Metal",
    route: "mechanical-metal",
    sub: [],
  },
  {
    id: "2",
    name: "mechanical-plastic",
    field: "기계가공-플라스틱",
    field_jp: "기계가공-플라스틱",
    field_en: "Mechanial Process-Plastic",
    route: "mechanical-plastic",
    sub: [],
  },
  {
    id: "3",
    name: "ceramic",
    field: "세라믹",
    field_jp: "세라믹",
    field_en: "Ceramic",
    route: "ceramic",
    sub: [],
  },
  {
    id: "4",
    name: "mold-parts",
    field: "금형부품",
    field_jp: "금형부품",
    field_en: "Mold Parts",

    route: "mold-parts",
    sub: [],
  },
  {
    id: "5",
    name: "electro-forming",
    field: "전주",
    field_jp: "전주",
    field_en: "Electro Froming",
    route: "electro-forming",
    sub: [],
  },
  {
    id: "6",
    name: "sintering",
    field: "소결",
    field_jp: "소결",
    field_en: "Sintering",
    route: "sintering",
    sub: [],
  },
  {
    id: "7",
    name: "electronic",
    field: "전기-전자",
    field_jp: "전기-전자",
    field_en: "Electronic-Electric",
    route: "electronic",
    sub: [],
  },
  {
    id: "8",
    name: "etching",
    field: "에칭",
    field_jp: "에칭",
    field_en: "Etching",
    route: "etching",
    sub: [],
  },
  {
    id: "9",
    name: "misc",
    field: "기타",
    field_jp: "기타",
    field_en: "Misc",
    route: "misc",
    sub: [],
  },
];
export const RndmassCategoriesData = [
  {
    id: "1",
    name: "auto-supplies",
    field: "자동차용품",
    field_jp: "자동차용품",
    field_en: "Auto Supplies",
    route: "auto-supplies",
    sub: [],
  },
  {
    id: "2",
    name: "kitchenware",
    field: "주방용품",
    field_jp: "주방용품",
    field_en: "Kitchen Wares",
    route: "kitchenware",
    sub: [],
  },
  {
    id: "3",
    name: "household",
    field: "생활용품",
    field_jp: "생활용품",
    field_en: "Household Supplies",
    route: "household",
    sub: [],
  },
  {
    id: "4",
    name: "office",
    field: "사무용품",
    field_jp: "사무용품",
    field_en: "Office Supplies",
    route: "office",
    sub: [],
  },
  {
    id: "5",
    name: "electro",
    field: "전기전자",
    field_jp: "전기전자",
    field_en: "Electronics",
    route: "electro",
    sub: [],
  },
  {
    id: "6",
    name: "misc",
    field: "기타",
    field_jp: "기타",
    field_en: "ETC",
    route: "misc",
    sub: [],
  },
  {
    id: "7",
    name: "flow",
    field: "개발FLOW",
    field_jp: "개발FLOW",
    field_en: "R&D FLOW",
    route: "flow",
    sub: [],
  },
];
export const DesksCategoriesData = [
  {
    id: "1",
    name: "desks",
    field: "데스크탑 데스크",
    field_jp: "데스크탑 데스크",
    field_en: "Desktop Desk",
    route: "desks",
  },
];

export const DisplayCategoriesData = [
  {
    id: "1",
    name: "display",
    field: "진열집기",
    field_jp: "진열집기",
    field_en: "Store Display",
    route: "display",
  },
];

export const bizAreaMenu = [
  {
    id: "1",
    name: "rnd-mass",
    field: "완제품-개발용역",
    field_jp: "완제품-개발용역",
    field_en: "R&D - Mass Production Div",
    route: "rnd-mass",
    categories: RndmassCategoriesData,
  },

  {
    id: "2",
    name: "precision-parts",
    field: "정밀부품",
    field_jp: "精密部品",
    field_en: "Precision Components Div",
    route: "precision-parts",
    categories: PrecisionCategoriesData,
  },
  {
    id: "3",
    name: "mold-mass",
    field: "금형사업",
    field_jp: "金型事業",
    field_en: "Mold and Die Div",
    route: "mold-mass",
    categories: MoldCategoriesData,
  },
];

export const companyMenu = [
  {
    id: "1",
    name: "about",
    field: "회사 개요",
    field_jp: "회사 개요",
    field_en: "About us",
    route: "about",
    active: false,
  },
  // {
  //   id: '2',
  //   name: 'greetings',
  //   field: '인사말',
  //   field_jp: '대표이사 인사말',
  //   field_en: 'R&D / Mass Production',
  //   route: 'greetings',
  //   active: false,
  // },
  {
    id: "3",
    name: "businesses",
    field: "사업 개요",
    field_jp: "사업 개요",
    field_en: "Business Area",
    route: "businesses",
    active: false,
  },
  {
    id: "4",
    name: "direction",
    field: "오시는 길",
    field_jp: "오시는 길",
    field_en: "Direction",
    route: "direction",
    active: false,
  },
];

export const TopMenu = [
  {
    id: "1",
    name: "company",
    field: "회사소개",
    field_jp: "회사소개",
    field_en: "COMPANY",
    route: "company",
  },

  {
    id: "2",
    name: "precision-parts",
    field: "정밀부품",
    field_jp: "정밀부품",
    field_en: "Precision Components",
    route: "precision-parts",
  },
  {
    id: "3",
    name: "mold-mass",
    field: "금형사업",
    field_jp: "금형사업",
    field_en: "Mold & Die",
    route: "mold-mass",
  },
  {
    id: "4",
    name: "rnd-mass",
    field: "완제품-개발용역",
    field_jp: "완제품-개발용역",
    field_en: "R&D MassProduction Div",
    route: "rnd-mass",
  },
  {
    id: "5",
    name: "tech-info",
    field: "기술정보",
    field_jp: "기술정보",
    field_en: "Technology Info",
    route: "tech-info",
  },
  // {
  //   id: '5',
  //   name: 'community',
  //   field: '게시판',
  //   field_jp: '게시판',
  //   field_en: 'Community',
  //   route: 'community',
  // },
];
// export const TopRightMenu = [
// //   ,
// //   {
// //     id: '1',
// //     name: 'login',
// //     field: 'Login',
// //     field_jp: 'Login',
// //     field_en: 'Login',
// //     route: 'login',
// //   },
// //   {
// //     id: '1',
// //     name: 'login',
// //     field: 'Login',
// //     field_jp: 'Login',
// //     field_en: 'Login',
// //     route: 'login',
// //   },
// // ];
// subMenu: [
//   {
//     id: '1',
//     name: 'about',
//     field: '회사 개요',
//     field_jp: '회사 개요',
//     field_en: 'About Company',
//     route: 'about',

//     active: false,
//   },
//   {
//     id: '2',
//     name: 'greetings',
//     field: '인사말',
//     field_jp: '대표이사 인사말',
//     field_en: 'R&D / Mass Production',
//     route: 'greetings',
//     active: false,
//   },
//   {
//     id: '3',
//     name: 'businesses',
//     field: '사업 개요',
//     field_jp: '사업 개요',
//     field_en: 'Business Fields',
//     route: 'businesses',
//     active: false,
//   },
//   {
//     id: '4',
//     name: 'direction',
//     field: '오시는 길',
//     field_jp: '오시는 길',
//     field_en: 'Direction',
//     route: 'direction',
//     active: false,
//   },
// ],
// },
// {
//   title: 'tech-info',
//   titleKR: '기술정보',
//   field_jp: '기술정보',
//   titleEN: 'TECHNOLOGY',
//   subMenu: [
//     {
//       id: '1',
//       name: 'tech-info',
//       field: '기술정보 1',
//       field_jp: '기술정보 1',
//       field_en: 'Technical Informations 1',
//       route: 'business/tech-info1',
//       bizRoute: 'business/tech-info1',
//     },
//   ],
// },

// {
//   title: 'business',
//   titleKR: '사업분야',
//   titleJP: '사업분야',
//   titleEN: 'BUSINESS',
//   subMenu: [
//     {
//       id: '1',
//       name: 'rnd-mass',
//       field: '완제품/개발용역',
//       field_jp: '완제품/개발용역',
//       field_en: 'R&D - Mass Production',
//       route: 'rnd-mass',
//       categories: RndmassCategoriesData,
//       // bizRoute: 'business/rnd',
//     },

//     {
//       id: '2',
//       name: 'precision-parts',
//       field: '정밀부품',
//       field_jp: '精密部品',
//       field_en: 'Precision Mold Components',
//       route: 'precision-parts',
//       categories: PrecisionCategoriesData,
//     },
//     {
//       id: '3',
//       name: 'mold-mass',
//       field: '금형&양산',
//       field_jp: '金型事業',
//       field_en: 'Mold and Mass Production',
//       route: 'mold-mass',
//       categories: MoldCategoriesData,
//     },
//     // {
//     //   id: '4',
//     //   name: 'display',
//     //   field: '진열집기',
//     //   field_jp: '진열집기',
//     //   field_en: 'Display Racks',
//     //   route: 'display',
//     //   categories: DisplayCategoriesData,
//     // },
//     // {
//     //   id: '5',
//     //   name: 'desks',
//     //   field: '데스크탑 데스크',
//     //   field_jp: '데스크탑 데스크',
//     //   field_en: 'Desktop Desk',
//     //   route: 'desks',
//     //   categories: DesksCategoriesData,
//     // },
//   ],
export const techCategoriesData = [
  {
    id: "1",
    name: "electro-mechanic",
    field: "기계전자",
    field_jp: "기계전자",
    field_en: "Electro Mechnics",
    route: "electro-mechanic",
    sub: [],
  },
  {
    id: "2",
    name: "mold-die",
    field: "금형기술",
    field_jp: "금형기술",
    field_en: "Mold & Die",
    route: "mold-die",
    sub: [],
  },
  {
    id: "3",
    name: "product-dev",
    field: "제품개발",
    field_jp: "제품개발",
    field_en: "Product Dev",
    route: "product-dev",
    sub: [],
  },
];
// },
export const categoriesData = [
  { name: "rnd-mass", data: RndmassCategoriesData },
  { name: "precision-parts", data: PrecisionCategoriesData },
  { name: "mold-mass", data: MoldCategoriesData },
  { name: "tech-info", data: techCategoriesData },
  // { name:'tech-info',data: TechinfoCategoriesData}
  // { name: 'display', data: DisplayCategoriesData },
  // { name: 'desks', data: DesksCategoriesData },
  // {name: "rnd", data:RndmassCategoriesData}
];
export const bizMenuData = [
  { business: "rnd-mass", categories: RndmassCategoriesData },
  { business: "precision-parts", categories: PrecisionCategoriesData },
  { business: "mold-mass", categories: MoldCategoriesData },
  { business: "tech-info", categories: techCategoriesData },
  // { name:'tech-info',data: TechinfoCategoriesData}
  // { name: 'display', data: DisplayCategoriesData },
  // { name: 'desks', data: DesksCategoriesData },
  // {name: "rnd", data:RndmassCategoriesData}
];

// export const devProcessData = [
//   {
//     id: '1',
//     name: 'semi-conductor',
//     field: '반도체 장비',
//     field_jp: '반도체 장비',
//     field_en: 'Semicondcutor Equeipment',
//     route: 'semi-conductor',
//   },
//   {
//     id: '2',
//     name: 'robot',
//     field: '산업용 로보트',
//     field_jp: '산업용 로보트',
//     field_en: 'Industrial Robot',
//     route: 'robot',
//   },
//   {
//     id: '3',
//     name: 'display',
//     field: '디스플레이 장비 부품',
//     field_jp: '디스플레이 장비 부품',
//     field_en: 'Component for Display Equipment',
//     route: 'display',
//   },
//   {
//     id: '4',
//     name: 'medical',
//     field: '의료 장비 부품',
//     field_jp: '의료 장비 부품',
//     field_en: 'Component for Medical Equipment',
//     route: 'medical',
//   },
//   {
//     id: '5',
//     name: 'auto',
//     field: '자동차 용품',
//     field_jp: '자동차 용품',
//     field_en: 'Auto Supplies',
//     route: 'auto',
//   },
//   {
//     id: '6',
//     name: 'electro',
//     field: '전기 전자 OA',
//     field_jp: '전기 전자 OA',
//     field_en: 'Electric-Electro OA',
//     route: 'electro',
//   },
//   {
//     id: '7',
//     name: 'pachinko',
//     field: '파친코 부품',
//     field_jp: '파친코 부품',
//     field_en: 'Component for Pachiko Equipment',
//     route: 'pachinko',
//   },
//   {
//     id: '8',
//     name: 'home',
//     field: '가정용품 기타',
//     field_jp: '가전 기타',
//     field_en: 'Home Appliances & Misc',
//     route: 'home',
//   },
// ];
export const materialsData = [
  {
    id: "1",
    name: "ceramic",
    field: "세라믹",
    field_jp: "세라믹",
    field_en: "Ceramic",
    route: "ceramic",
  },
  {
    id: "2",
    name: "aluminum",
    field: "알루미늄",
    field_jp: "알루미늄",
    field_en: "Aluminum",
    route: "aluminum",
  },

  {
    id: "3",
    name: "stainless",
    field: "스테인레스",
    field_jp: "스테인레스",
    field_en: "Stainless Steel",
    route: "stainless",
  },
  {
    id: "4",
    name: "copper",
    field: "동",
    field_jp: "동",
    field_en: "Copper",
    route: "copper",
  },
  {
    id: "5",
    name: "eng-plastic",
    field: "엔지니어링 플라스틱",
    field_jp: "엔지니어링 플라스틱",
    field_en: "Engineering Plastic",
    route: "eng-plastic",
  },
  {
    id: "6",
    name: "special-steel",
    field: "특수철",
    field_jp: "특수철",
    field_en: "Stainless Steel",
    route: "special-steel",
  },
  {
    id: "7",
    name: "titanium",
    field: "티타늄",
    field_jp: "티타늄",
    field_en: "Stainless Steel",
    route: "titanium",
  },
  {
    id: "8",
    name: "mics",
    field: "기타",
    field_jp: "기타",
    field_en: "Miscellaneous Materials",
    route: "mics",
  },
];

export const applicationsData = [
  {
    id: "1",
    name: "semi-conductor",
    field: "반도체 장비",
    field_jp: "반도체 장비",
    field_en: "Semicondcutor Equeipment",
    route: "semi-conductor",
  },
  {
    id: "2",
    name: "robot",
    field: "산업용 로보트",
    field_jp: "산업용 로보트",
    field_en: "Industrial Robot",
    route: "robot",
  },
  {
    id: "3",
    name: "display",
    field: "디스플레이 장비 부품",
    field_jp: "디스플레이 장비 부품",
    field_en: "Component for Display Equipment",
    route: "display",
  },
  {
    id: "4",
    name: "medical",
    field: "의료 장비 부품",
    field_jp: "의료 장비 부품",
    field_en: "Component for Medical Equipment",
    route: "medical",
  },
  {
    id: "5",
    name: "auto",
    field: "자동차 용품",
    field_jp: "자동차 용품",
    field_en: "Auto Supplies",
    route: "auto",
  },
  {
    id: "6",
    name: "electro",
    field: "전기 전자 OA",
    field_jp: "전기 전자 OA",
    field_en: "Electric-Electro OA",
    route: "electro",
  },
  {
    id: "7",
    name: "pachinko",
    field: "파친코 부품",
    field_jp: "파친코 부품",
    field_en: "Component for Pachiko Equipment",
    route: "pachinko",
  },
  {
    id: "8",
    name: "home",
    field: "가정용품 기타",
    field_jp: "가전 기타",
    field_en: "Home Appliances & Misc",
    route: "home",
  },
  {
    id: "9",
    name: "idea",
    field: "아이디어상품 기타",
    field_jp: "아이디어상품 기타",
    field_en: "Idea Products",
    route: "idea",
  },
  {
    id: "10",
    name: "post",
    field: "후가공",
    field_jp: "후가공",
    field_en: "Post Processing",
    route: "post",
  },
  // {
  //   id: '11',
  //   name: 'idea',
  //   field: '아이디어상품 기타',
  //   field_jp: '아이디어상품 기타',
  //   field_en: 'Idea Products',
  //   route: 'idea',
  // },
];

export const searchTitles = [
  {
    id: "1",
    name: "applications",
    field: "응용분야",
    field_jp: "응용분야",
    field_en: "Applications",
    searchFields: applicationsData,
  },
  {
    id: "2",
    name: "materials",
    field: "원재료",
    field_jp: "원재료",
    field_en: "Materials",
    searchTitles: materialsData,
  },
  //   {
  //     id: '3',
  //     name: 'dev-process',
  //     field: '개발단계',
  //     field_jp: '개발단계',
  //     field_en: 'Development-Process',
  //     searchTitles: devProcessData,
  //   },
];
export const langMode = "en";
