import Header from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import { Toaster } from "@/components/ui/toaster";
import Provider from "./_trpc/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  // console.log("session", session);
  const isLoggedIn = session === null ? false : true;
  // console.log("isLoggedIn", isLoggedIn);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Header isLoggedIn={isLoggedIn} />
          <main className="mt-32 mx-auto px-4 max-w-2xl lg:max-w-7xl lg:mx-auto">
            {children}
          </main>
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
